services:
  app:
    build: .
    gpus: all

    # Ключевые правки для PyTorch DataLoader и больших батчей
    shm_size: "2gb"     # увеличивает /dev/shm внутри контейнера

    ports:
      - "8005:8000"
    volumes:
      - ./train_gnn.yaml:/app/train_gnn.yaml
      - ./epoch:/app/epoch
      - ./logs:/app/logs
      - ./tensorboard:/app/tensorboard

    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/.cache/huggingface

    restart: unless-stopped
