services:
  app:
    build: .
    image: sandrro/genbuilder_vector:0.4
    gpus: all

    shm_size: 8g

    ports:
      - "8005:8000"
    volumes:
      - ./train_gnn.yaml:/app/train_gnn.yaml
      - ./epoch:/app/epoch
      - ./logs:/app/logs
      - ./tensorboard:/app/tensorboard

    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/.cache/huggingface

    restart: unless-stopped
