services:

  app:
    build: .
    gpus: all
    ports:
      - "8005:8000"
    volumes:
      - ./train_gnn.yaml:/app/train_gnn.yaml
      - ./epoch:/app/epoch
      - ./logs:/app/logs
      - ./tensorboard:/app/tensorboard
