name: genbuilder-inference
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - cpuonly
  - pytorch-scatter=2.1.2
  - pytorch-sparse=0.6.18
  - pytorch-geometric=2.5.3
  - numpy<2.0
  - networkx=3.2.1
  - shapely=2.0.4
  - pillow=10.3.0
  - pyyaml=6.0.1
  - huggingface_hub=0.25.2
  - scikit-geometry=0.1.2
