name: genbuilder-inference
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - pytorch-cuda=12.1      # стягивает CUDA runtime в окружение
  - numpy<2.0
  - networkx
  - shapely
  - pillow
  - pyyaml
  - huggingface_hub
  - scikit-geometry=0.1.2
  - uvicorn
  - fastapi
  - pip
  # опционально, если нужно:
  # - torchvision=0.16.0
