###############################  Training setting   ############################
gpu_ids : 
  - 0

clean_cache : False
save_record : True
is_multigpu : False
skip_single : False  # skip graphs with 1 node and 0 edges during training

save_epoch : 5
val_ratio : 0.2
total_epochs : 10
start_epoch : 0


###################################   GlobalMapper setting   #######################################
is_Teaser : False
is_conditional_block : True        # <-- было False, теперь True
is_input_road: True
encode_cnn : True                  # оставить True, если используешь *_cnn модель
is_blockplanner : False

cond_dim: 0                        # autodetect from _zones_map.json

attten_net : 
  - 'TransformerConv'
  - 'GATConv'
  - 'SAGEConv'

convlayer : 'GATConv' #'ResGatedGraphConv' #'SuperGATConv' #'GATv2Conv' # 'GPSConv'   #'GCNConv' #'NaiveMsgPass'  #'TransformerConv'  #'GATConv'  #'SAGEConv'    #'NaiveMsgPass'  #'SAGEConv'
aggr : 'Max'  # 'Mean'
lr : 0.001
n_ft_dim : 256
block_latent_dim : 20
head_num : 12  # only for GAT
batch_size : 10
latent_dim: 1024
template_width : 30
template_height : 4
max_nodes_override : null  # manually cap max nodes
dropout_p : 0.1


################################    weight setting  #########################################################
exist_weight : 3.0
pos_weight : 4.0
kld_weight : 0.5
size_weight : 4.0
extsum_weight : 2.0
shape_weight : 0.05
iou_weight : 1.0
height_weight : 4.0




####################################     resume setting     #####################################################
resume : False
resume_dir : 'Your resume folder'
import_name : 'latest'
resume_epoch : 400

